version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "sa-east-1"
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
      - cd lambdas-functions && npm install && cd ..
      - cdk version
  pre_build:
    commands:
      - cdk bootstrap
  build:
    commands:
      - cdk version
      - cdk deploy --require-approval never